apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
  tags:
    - desy
    - ${{ values.architectureType }}
    {%- if values.headerType %}
    - layout-${{ values.headerType }}
    {%- endif %}
    {%- if values.hasSidebar %}
    - with-sidebar
    {%- endif %}
    {%- if values.hasSubheader %}
    - with-subheader
    {%- endif %}
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner | default("user:guest", true) }}
